### ISSUE TITLE
Configuration error: Invalid URL, check the connection configuration and try again.

### ISSUE THREAD

**Issue by Bl4ckLine** [iganeshk/LaMetric-System-Monitor#1]
Hello, 

I'm having an issue after generating my local push URL and setting it in the lametricSysMon.py file with my app Access token.
I'm getting the following message "Configuration error: Invalid URL, check the connection configuration and try again." when I run python3 lametricSysMon.py 

I tried a telnet on my lametric IP Adress with the port used in the URL and it's working. 
And I'm able to connect to my lametric app via Postman (on windows)

I'm doing this on Ubuntu 

Regards

**Comment by gyaneesh** [comment]
Pull the latest code and give it a shot now (git fetch && git pull from the latmetric directory).

**Comment by Bl4ckLine** [comment]
Using Python3 on Windows instead of using it on my Ubuntu WSL fixed the issue.
